### ISSUE TITLE
Heads-up: UB due to misuse of mem::uninitialized will soon lead to panic

### ISSUE THREAD

**Issue by RalfJung** [typester/frostflake-rs#3]
This crate uses an ancient version of crossbeam, causing UB by ["Producing an invalid value"](https://doc.rust-lang.org/reference/behavior-considered-undefined.html). Concretely, it creates an arbitrary  `T` with `mem::uninitialized()`. In the near future the call to `mem::uninitialized()` [will panic to avoid UB](https://github.com/rust-lang/rust/pull/66059), and [our crater run](https://github.com/rust-lang/rust/pull/66059#issuecomment-575164263) determined that this crate will be affected.

Updating to the latest crossbeam should fix this.

**Comment by typester** [comment]
Thanks, I've updated crossbeam to the latest version.
